### ISSUE TITLE
Add LICENSE.txt

### ISSUE THREAD

**Issue by davelab6** [fontfish/BiangFont#1]
I suggest OFL :)

**Comment by fontfish** [comment]
Thank you very much for the reminder! The SIL OFL does look like a good option, and has clear implementation guidelines. I have added it in LICENSE.txt, as well as making a small plethora of changes for font names, file structure, information and documentation, etc.

If you notice any errors or think I've implemented anything improperly, please let me know. For now, I will mark this issue as closed.
